### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Stan92** [peter-evans/osrm-backend-k8s#54]
Hi,
It's not an issue but probably a silly newbie question.
I'll try to run the K8s configuration that you've explained using GCP.
My question is : 
Do I have to run the yaml files from the Google Shell or from my local computer?
And btw, still about GCP, do you have any advice for a correct configuration (number of vCPU and Ram) for managing a pbf file like France?

**Comment by peter-evans** [comment]
Hi @Stan92,

The Kubernetes yaml files must be executed with the kubectl command-line tool. I think this is available in the Google Shell that you can access via the GCP console. However, I recommend testing your cluster and managing it from your local workstation. For this you need the gcloud and kubectl command-line tools. You can see how to configure them [here](https://cloud.google.com/kubernetes-engine/docs/quickstart) and [here](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl).

For building a single country size graph I recommend at least 4 cores and 16GB RAM, preferably more. You could, for example, build with 32GB RAM and scale back to 16-8GB for runtime depending on your requirements when it's running in production. You also need plenty of disk space to store the pbf file and build stages. Maybe 200-300GB depending on the size of the graph.

**Comment by Stan92** [comment]
Hi @peter-evans 
I thank you so much for your explanations.. 
Everything seems to work like a charm.
I've also noticed that I got evicted pods (I think it's about memory) than for my test, I increased the memory size and reduced the number of replicas (to 1) for testing..


I had to add these lines (within the canary.yaml file) 

```
  selector:
    matchLabels:
      app: osrm-car

```

I thank you once again.
